// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AskDirectory():Promise<string>;

export function GetDirectory(arg1:string):Promise<Array<string>>;

export function IsFile(arg1:string):Promise<boolean>;
