// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function AskDirectory():Promise<string>;

export function Boxdims_is_installed():Promise<backend.Boxdims>;

export function CheckWorkspace():Promise<string>;

export function ChooseDistro(arg1:string):Promise<void>;

export function CloseConfWorkspace():Promise<void>;

export function Compile(arg1:string,arg2:string):Promise<string>;

export function Detect_tex_distros():Promise<backend.Conf>;

export function GetContent(arg1:string):Promise<string>;

export function GetDirectory(arg1:string):Promise<Array<string>>;

export function GetPDF(arg1:string):Promise<string>;

export function IsFile(arg1:string):Promise<boolean>;

export function SaveContent(arg1:string,arg2:string):Promise<boolean>;
