// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AskDirectory() {
  return window['go']['backend']['App']['AskDirectory']();
}

export function CheckWorkspace() {
  return window['go']['backend']['App']['CheckWorkspace']();
}

export function CloseConfWorkspace() {
  return window['go']['backend']['App']['CloseConfWorkspace']();
}

export function GetContent(arg1) {
  return window['go']['backend']['App']['GetContent'](arg1);
}

export function GetDirectory(arg1) {
  return window['go']['backend']['App']['GetDirectory'](arg1);
}

export function GetPDF(arg1) {
  return window['go']['backend']['App']['GetPDF'](arg1);
}

export function IsFile(arg1) {
  return window['go']['backend']['App']['IsFile'](arg1);
}

export function SaveContent(arg1, arg2) {
  return window['go']['backend']['App']['SaveContent'](arg1, arg2);
}
