// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AskDirectory():Promise<string>;

export function CheckWorkspace():Promise<string>;

export function CloseConfWorkspace():Promise<void>;

export function Detect_tex_distros():Promise<void>;

export function GetContent(arg1:string):Promise<string>;

export function GetDirectory(arg1:string):Promise<Array<string>>;

export function GetPDF(arg1:string):Promise<string>;

export function IsFile(arg1:string):Promise<boolean>;

export function SaveContent(arg1:string,arg2:string):Promise<boolean>;
