// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AskDirectory() {
  return window['go']['main']['App']['AskDirectory']();
}

export function GetDirectory(arg1) {
  return window['go']['main']['App']['GetDirectory'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
